[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_staking = "5DZyDdBj7cgqzJc8KuQjexxpY38uNLYm3uYbojGQXFdJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
